name: PackPrisonsCore
version: 1.0-SNAPSHOT
main: net.packprisons.core.PackPrisonsCore
authors: [ Indeedious, Matt, BradonLea, Tucker ]
description: The Core plugin for PackPrisons
website: https://www.packprisons.net
api-version: 1.12
commands:
  fly:
    aliases: [f]
  message:
    aliases: [msg, tell]
  reply:
    aliases: [r]
  vanish:
    aliases: [v]
  gamemode:
    aliases: [gm]
  help:
    description: Displays a Help Message
  tpa:
    description: Asks the specified player to allow the sender to teleport to them
  clearchat:
    aliases: [cc]
  inventorysee:
    aliases: [invsee]
  tpall:
    aliases: [ta]
  ping:
    description: Displays your Ping
  teleport:
    aliases: [tp]
