name: PackPrisonsCore
version: ${project.version}
main: net.packprisons.core.PackPrisonsCore
api-version: 1.16
authors: [ Indeedious, Matt, BradonLea, Tucker ]
description: The Core plugin for PackPrisons
website: https://www.packprisons.net
commands:
  fly:
    aliases: [f]
  message:
    aliases: [msg, tell]
  reply:
    aliases: [r]
  vanish:
    aliases: [v]
  gamemode:
    aliases: [gm]
  help:
    description: Displays a Help Message
  tpa:
    description: Asks the specified player to allow the sender to teleport to them
  clearchat:
    aliases: [cc]
  invsee:
    aliases: [is]
  tpall:
    aliases: [ta]
